authapp/urls.py
from django.urls import path, include
import authapp.views as authapp


app_name = 'authurls'
urlpatterns = [
    path('', authapp.login, name='authlogin'),
    path('logout/', authapp.logout, name='authlogout'),
    path('registration/', authapp.registration, name='authreg'),
]

# path('register/', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name='registration_register')

dictionary/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp



urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('authapp.urls', namespace='auth')), # в теплейтс, адрес ссылки для перехода на страницу логин,
                                                               # будет адрес auth:authlogin, где auth - это здешний
                                                               # namespace, а authlogin - name в authapp/urls
    path('userpage/', include('userapp.urls', namespace='userapp')),
    path('', mainapp.mainpage, name='mainpage'),
    path('userpage/excerpts/', include('excerptapp.urls', namespace='excerptapp')),
    path('userpage/phrases/', include('phraseapp.urls', namespace='phraseapp')),
]

phraseapp/urls.py
from django.urls import path, include
import phraseapp.views as phraseapp


app_name = 'phrasesurls'
urlpatterns = [
    path('<user_pk>/', phraseapp.CreatePhraseView.as_view(), name='createphrase'),
    path('<user_pk>/<phrase_pk>/', phraseapp.EditPhraseView.as_view(), name='editphrase')
]

userapp/urls.py
from django.urls import path, include
import userapp.views as userapp
from django.views import View


app_name = 'userdicturls'
urlpatterns = [
    path('', userapp.UserpageListView.as_view(), name='userpage'),
    path('<user_pk>/dictionaries', userapp.dictionaries, name='dictionaries'),
    # path('<user_pk>/dictionaries', userapp.DictionariesListView.as_view(), name='dictionaries'),
    path('<user_pk>/dictionaries/addauthor', userapp.addauthor, name='addauthor'),
    path('<user_pk>/dictionaries/<author_pk>/authoredit', userapp.authoredit, name='authoredit'),
    path('<user_pk>/dictionaries/<author_pk>/', userapp.books, name='books'),
    path('<user_pk>/dictionaries/<author_pk>/addbook', userapp.addbook, name='addbook'),
    path('<user_pk>/dictionaries/<author_pk>/<book_pk>/bookedit', userapp.bookedit, name='bookedit'),
    path('<user_pk>/dictionaries/<author_pk>/<book_pk>/', userapp.words, name='words'),
    path('<user_pk>/dictionaries/<author_pk>/<book_pk>/addword', userapp.addword, name='addword'),
    path('<user_pk>/dictionaries/<author_pk>/<book_pk>/edit/<word_pk>/', userapp.wordedit, name='wordedit'),
]

userapp/models.py
from django.conf import settings
from django.db import models


# Create your models here.

#Модель Dictionary это бывшая модель Author; поскольку каждый пользователь будет создавать словари, то первое звено
#цепи в любом случае автор, поэтому словари пользователя это перечень авторов
class Dictionary(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_authors")
    # related_name, чтобы можно было обращаться к объектам модели Dictionary из модели DictUser
    name = models.CharField(verbose_name="Author's name", max_length=64)
    last_name = models.CharField(verbose_name="Author's last name", max_length=64)

    def __str__(self):
        return "{} {}".format(self.name, self.last_name)

class Book(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_books")
    author = models.ForeignKey(Dictionary, on_delete=models.CASCADE, related_name='author_books')
    # related_name, чтобы можно было обращаться к объектам модели Book из модели Dictionary
    title = models.CharField(verbose_name="Book's title", max_length=128)
    image = models.ImageField(upload_to="Book's image", blank=True)

    def __str__(self):
        return "{}".format(self.title)

class Word(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_words")
    author = models.ForeignKey(Dictionary, on_delete=models.CASCADE, related_name='author_words')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='words')
    # related_name, чтобы можно было обращаться к объектам модели Word из модели Book
    word = models.CharField(verbose_name='word', max_length=128)
    translation = models.CharField(verbose_name='translation', max_length=128)
    context = models.TextField(verbose_name='context', blank=True)
    note = models.TextField(verbose_name='note', blank=True)

    def __str__(self):
        return "{}".format(self.word)










# class Word(models.Model):
#     word = models.CharField(verbose_name='word', max_length=128, default=True)
#
#     def __str__(self):
#         return self.word
#
# class Book(models.Model):
#     title = models.CharField(verbose_name="Book's title", max_length=128)
#     members = models.ManyToManyField(Word, through='Membership')
#
#     def __str__(self):
#         return self.title
#
# class Membership(models.Model):
#     word = models.ForeignKey(Word, on_delete=models.CASCADE)
#     book = models.ForeignKey(Book, on_delete=models.CASCADE)

userapp/forms.py
from django import forms
from .models import Dictionary, Book, Word


#данная форма рисуется по модели Dictionary, но пользователя не выводим, оно будет заполняться автоматически
class AuthorCreationForm(forms.ModelForm):
    class Meta:
            model = Dictionary
            fields = ('name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(AuthorCreationForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = "Author's name"
        self.fields['last_name'].widget.attrs['placeholder'] = "Author's surname"

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class BookCreationForm(forms.ModelForm):
    class Meta:
            model = Book
            fields = ('title',)

    def __init__(self, *args, **kwargs):
        super(BookCreationForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = "Book's title"
        self.fields['title'].label = ""

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class WordCreationForm(forms.ModelForm):
    class Meta:
            model = Word
            fields = ('word', 'translation', 'context', 'note')

    def __init__(self, *args, **kwargs):
        super(WordCreationForm, self).__init__(*args, **kwargs)
        self.fields['word'].widget.attrs['placeholder'] = "Word"
        self.fields['translation'].widget.attrs['placeholder'] = "Translation"
        self.fields['context'].widget.attrs['placeholder'] = "Add context"
        self.fields['note'].widget.attrs['placeholder'] = "Add note"

        for field in self.fields:
            self.fields[field].label = ""
            self.fields[field].widget.attrs['class'] = 'form-control'

userapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from userapp.mixins import Mixins_userapp
from .forms import AuthorCreationForm, BookCreationForm, WordCreationForm
from .models import Dictionary, Book, Word
from phraseapp.models import PhraseModel
from excerptapp.models import ExcerptModel
from django.views.generic.list import ListView

# class UserpageListView(ListView): # cbv with two models
#     template_name = 'userapp/userpage.html'
#     context_object_name = 'phrases' # create var so that it is on the page and later we'll take 'phrases' and define it as PhraseModel
#
#     def get_queryset(self): # on template calls as objects
#         return Dictionary.objects.all()
#
#     def get_context_data(self, **kwargs):
#         context = super(UserpageListView, self).get_context_data(**kwargs) # call get_context_data method via inheritance from class UserpageListView
#         context['phrases'] = PhraseModel.objects.all() # on template calls as phrases
#         return context

# another way with mixin

# class UserpageListView(Mixins_userapp, View):
#     def get(self, request, *args, **kwargs):
#         mixin_data = super(UserpageListView, self)
#         context = mixin_data.get_context_data()
#         return render(request, 'userapp/userpage.html', context)

class UserpageListView(Mixins_userapp, View):
    template = 'userapp/userpage.html'


@login_required
def dictionaries(request, user_pk):
    dict_items = Dictionary.objects.filter(user=request.user.pk)
    check = 'контролер авторов считывается'

    if request.method == 'POST':
        form = AuthorCreationForm(request.POST)
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.save()
            return HttpResponseRedirect(reverse('userapp:dictionaries', args=[request.user.pk]))
    else:
        form = AuthorCreationForm()

    content = {
        'user_pk': request.user.pk,
        'dicts': dict_items,
        'test': check,
        'author_form': form
    }

    return render(request, 'userapp/dictionaries.html', content)

@login_required
@transaction.atomic
def addauthor(request, user_pk):

    if request.method == 'POST':
        form = AuthorCreationForm(request.POST)
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.save()
            return HttpResponseRedirect(reverse('userapp:dictionaries', args=[request.user.pk]))
    else:
        form = AuthorCreationForm()

    content = {
        'user_pk': request.user.pk,
        'author_form': form
    }

    return render(request, 'userapp/addauthor.html', content)

@login_required
@transaction.atomic
def authoredit(request, user_pk, author_pk):
    dictionary_instance = get_object_or_404(Dictionary, pk=author_pk)
    form = AuthorCreationForm(request.POST, instance=dictionary_instance)

    if request.method == 'POST':
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.save()
            return HttpResponseRedirect(reverse('userapp:books', args=[request.user.pk, author_pk]))
    else:
        form = AuthorCreationForm(instance=dictionary_instance)

    content = {
        'user_pk': request.user.pk,
        'author_pk': author_pk,
        'authoredit_form': form
    }

    return render(request, 'userapp/authoredit.html', content)

@login_required
@transaction.atomic
def books(request, user_pk, author_pk):
    book_items = Book.objects.filter(author=author_pk, user=request.user.pk)
    author_instance = get_object_or_404(Dictionary, pk=author_pk)
    author_name = get_object_or_404(Dictionary, pk=author_pk)
    check = 'контролер книг автора считывается'

    if request.method == 'POST':
        form = BookCreationForm(request.POST)
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.author = author_instance
            response.save()
            return HttpResponseRedirect(reverse('userapp:books', args=[request.user.pk, author_pk]))
    else:
        form = BookCreationForm()

    content = {
        'author_name': author_name,
        'author_pk': author_pk,
        'books': book_items,
        'book_form': form,
        'test': check,
    }

    return render(request, 'userapp/books.html', content)

@login_required
@transaction.atomic
def addbook(request, user_pk, author_pk):
    author_instance = get_object_or_404(Dictionary, pk=author_pk)
    author_name = get_object_or_404(Dictionary, pk=author_pk)

    if request.method == 'POST':
        form = BookCreationForm(request.POST)
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.author = author_instance
            response.save()
            return HttpResponseRedirect(reverse('userapp:books', args=[request.user.pk, author_pk]))
    else:
        form = BookCreationForm()

    content = {
        'author_name': author_name,
        'author_pk': author_pk,
        'book_form': form,
    }

    return render(request, 'userapp/addbook.html', content)

@login_required
@transaction.atomic
def bookedit(request, user_pk, author_pk, book_pk):
    author_instance = get_object_or_404(Dictionary, pk=author_pk)
    author_name = get_object_or_404(Dictionary, pk=author_pk)

    book_instance = get_object_or_404(Book, pk=book_pk)
    form = BookCreationForm(request.POST, instance=book_instance)

    if request.method == 'POST':
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.author = author_instance
            response.save()
            return HttpResponseRedirect(reverse('userapp:words', args=[request.user.pk, author_pk, book_pk]))
    else:
        form = BookCreationForm(instance=book_instance)

    content = {
        'author_name': author_name,
        'author_pk': author_pk,
        'book_pk': book_pk,
        'bookedit_form': form,
    }

    return render(request, 'userapp/bookedit.html', content)

@login_required
def words(request, user_pk, author_pk, book_pk):
    word_items = Word.objects.filter(author=author_pk, user=request.user.pk, book=book_pk)
    author_instance = get_object_or_404(Dictionary, pk=author_pk)
    book_instance = get_object_or_404(Book, pk=book_pk)
    author_instance = get_object_or_404(Dictionary, pk=author_pk)
    book_instance = get_object_or_404(Book, pk=book_pk)
    check = 'контролер слов книги считывается'

    if request.method == 'POST':
        form = WordCreationForm(request.POST)
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.author = author_instance
            response.book = book_instance
            response.save()
            return HttpResponseRedirect(reverse('userapp:words', args=[request.user.pk, author_pk, book_pk]))
    else:
        form = WordCreationForm()

    content = {
        'author_name': author_instance,
        'book_title': book_instance,
        'author_pk': author_pk,
        'book_pk': book_pk,
        'words': word_items,
        'word_form': form,
        'test': check,
    }

    return render(request, 'userapp/words.html', content)

@login_required
@transaction.atomic
def addword(request, user_pk, author_pk, book_pk):
    author_instance = get_object_or_404(Dictionary, pk=author_pk)
    book_instance = get_object_or_404(Book, pk=book_pk)
    author_instance = get_object_or_404(Dictionary, pk=author_pk)
    book_instance = get_object_or_404(Book, pk=book_pk)

    if request.method == 'POST':
        form = WordCreationForm(request.POST)
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.author = author_instance
            response.book = book_instance
            response.save()
            return HttpResponseRedirect(reverse('userapp:words', args=[request.user.pk, author_pk, book_pk]))
    else:
        form = WordCreationForm()

    content = {
        'author_name': author_instance,
        'book_title': book_instance,
        'author_pk': author_pk,
        'book_pk': book_pk,
        'word_form': form,
    }

    return render(request, 'userapp/addword.html', content)

@login_required
@transaction.atomic
def wordedit(request, user_pk, author_pk, book_pk, word_pk):

    author_instance = get_object_or_404(Dictionary, pk=author_pk)
    book_instance = get_object_or_404(Book, pk=book_pk)
    word_instance = get_object_or_404(Word, pk=word_pk)

userapp/templates/userapp/authoredit.html
{% extends "userapp/base.html" %}
{% load static %}
{% block back %}
    <li class="nav-item"><a href="{% url 'userapp:books' user_pk=user.pk author_pk=author_pk %}" class="nav-link">Back to Books</a></li>
{% endblock %}
{% block content %}
    <div class="wrapper-userpage">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="shadow m-2 py-2">
                    <div class="col-sm-12 col-md-12">

                        <div class="row justify-content-center">
                            <div class="col-sm-12 col-md-12">
                                <p class="text-center">Author edit form:</p>
                            </div>
                        </div>

                        <form class="" action="{% url 'userapp:authoredit' user_pk=user.pk author_pk=author_pk %}" method="post">
                            {% csrf_token %}

                            <div class="row">
                                {% for i in authoredit_form %}
                                    <div class="col-sm-12 col-md-6">
                                        {{ i }}
                                    </div>
                                {% endfor %}
                            </div>

                            <div class="row">
                                <div class="col-sm-12 col-md-12">
                                    <input class="input-author" type="submit" value="Save">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

userapp/templates/userapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Welcome</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/v4-shims.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a href="#" class="navbar-brand">{{ user.username|capfirst }}</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-menu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="nav-menu">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a href="#" class="nav-link">Profile</a></li>
                <li class="nav-item"><a href="{% url 'auth:authlogout' %}" class="nav-link">Logout</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Your Dictionaries</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Your Excerpts</a></li>
                <li class="nav-item"><a href="{% url 'phraseapp:createphrase' user_pk=user.pk %}" class="nav-link">Your Phrases</a></li>
                {% block back %}
                {% endblock %}
                 <li class="nav-item ">
                    <ul class="navbar-nav text-white d-md-none d-lg-none d-sm-flex flex-row">
                        <li class="nav-item my-auto mr-auto"><i class="fas fa-share-alt "></i></li>
                        <li class="nav-item"><a href="#" class="nav-link"><i class="fab fa-facebook-f"></i></a></li>
                        <li class="nav-item ml-3"><a href="#" class="nav-link"><i class="fab fa-twitter"></i></a></li>
                        <li class="nav-item ml-3"><a href="#" class="nav-link"><i class="fa fa-vk" aria-hidden="true"></i></a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-bottom d-md-flex d-sm-none d-none">
        <p class="mb-0 text-white">&copy;All rights reserved.</p>
        <ul class="navbar-nav text-white ml-auto">
            <li class="nav-item my-auto mr-2"><i class="fas fa-share-alt"></i></li>
            <li class="nav-item ml-2"><a href="#" class="nav-link"><i class="fab fa-facebook-f"></i></a></li>
            <li class="nav-item ml-2"><a href="#" class="nav-link"><i class="fab fa-twitter"></i></a></li>
            <li class="nav-item ml-2"><a href="#" class="nav-link"><i class="fa fa-vk" aria-hidden="true"></i></a></li>
        </ul>
    </nav>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

userapp/templates/userapp/books.html
{% extends "userapp/base.html" %}
{% load static %}
{% block back %}
    <li class="nav-item"><a href="{% url 'userapp:dictionaries' user_pk=user.pk %}" class="nav-link">Back to Authors</a></li>
{% endblock %}

{% block content %}
    <div class="wrapper-userpage">
        <div class="container-fluid">
            <div class="row justify-content-center">

                <div class="col-md-5 d-none d-md-block my-1">
                    <div class="shadow p-1 mb-3">
                        <div class="row">
                            <div class="col-md-6">
                                <h6 class="mb-0">{{ author_name }}</h6>
                            </div>
                            <div class="col-md-6">
                                <button class="author-btn add-btn">
                                    <a href="{% url 'userapp:authoredit' user_pk=user.pk author_pk=author_pk %}">Edit author</a>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="shadow p-1">
                        <h6 class="text-center">Add book:</h6>
                        <form action="{% url 'userapp:books' user_pk=user.pk author_pk=author_pk %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                {% for i in book_form %}
                                    {{ i }}
                                {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <input class="input-author" type="submit" value="Save">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-sm-12 col-xs-12 d-md-none d-sm-block my-1">
                    <div class="shadow p-1">
                        <div class="row">
                            <div class="col-sm-12">
                                <h6 class="text-center">{{ author_name }}</h6>
                            </div>
                            <div class="col-sm-12">
                                <button class="author-btn add-btn">
                                    <a href="{% url 'userapp:authoredit' user_pk=user.pk author_pk=author_pk %}">Edit author</a>
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class="shadow p-1">
                        <button class="author-btn add-btn">
                            <a href="{% url 'userapp:addbook' user_pk=user.pk author_pk=author_pk %}">Add book</a>
                        </button>
                    </div>
                </div>

                <div class="col-sm-12 col-md-3 my-1 no-paddings-x">
                    <div class="shadow py-1">
                        <h6 class="text-center">Books:</h6>
                    {% for i in books %}
                        <div class="row m-1">
                            <button class="author-btn">
                                <a href="{% url 'userapp:words' user_pk=user.pk author_pk=author_pk book_pk=i.pk %}">{{ i.title }}</a>
                            </button>
                        </div>
                    {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

userapp/templates/userapp/dictionaries.html
{% extends "userapp/base.html" %}
{% load static %}

{% block back %}
    <li class="nav-item"><a href="{% url 'userapp:userpage' %}" class="nav-link">Back to userpage</a></li>
{% endblock %}

{% block content %}
    <div class="wrapper-userpage">
        <div class="container-fluid">
            <div class="row justify-content-center">

                <div class="col-md-5 d-none d-md-block my-1">
                    <div class="shadow p-1">
                        <h6 class="text-center">Add authors/dictionaries:</h6>
                        <form action="{% url 'userapp:dictionaries' user_pk=user.pk %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                {% for i in author_form %}
                                    {{ i }}
                                {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <input class="input-author" type="submit" value="Save">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-sm-12 d-md-none d-sm-block my-1">
                    <div class="shadow p-1">
                        <button class="author-btn add-btn">
                            <a href="{% url 'userapp:addauthor' user_pk=user.pk %}">Add authors/dictionaries</a>
                        </button>
                    </div>
                </div>

                <div class="col-sm-12 col-md-3 my-1 no-paddings-x">
                    <div class="shadow py-1">
                        <h6 class="text-center">Your authors/dictionaries:</h6>
                    {% for i in dicts %}
                        <div class="row m-1">
                            <button class="author-btn">
                                <a href="{% url 'userapp:books' user_pk=user.pk author_pk=i.pk %}">{{ i.last_name }}</a>
                            </button>
                        </div>
                    {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

userapp/templates/userapp/words.html
{% extends "userapp/base.html" %}
{% load static %}
{% block back %}
    <li class="nav-item"><a href="{% url 'userapp:books' user_pk=user.pk author_pk=author_pk %}" class="nav-link">Back to Books</a></li>
{% endblock %}
{% block content %}


    <div class="wrapper-userpage">
        <div class="container-fluid">
            <div class="row justify-content-center">

                <div class="col-md-3 my-1">
                    <div class="shadow p-1">
                        <div class="row">
                            <div class="col-md-12">
                                <p class="mb-0"><span class="h6">Author:</span> {{ author_name }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p class="mb-0"><span class="h6">Book:</span> {{ book_title }}</p>
                            </div>
                        </div>
                        <div class="row mb-1">
                            <div class="col-md-12">
                                <button class="author-btn add-btn">
                                    <a href="{% url 'userapp:bookedit' user_pk=user.pk author_pk=author_pk book_pk=book_pk %}">Edit Book Title</a>
                                </button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <button class="author-btn add-btn">
                                    <a href="{% url 'userapp:addword' user_pk=user.pk author_pk=author_pk book_pk=book_pk %}">Add word</a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-5 my-1 no-paddings-x">
                    <div class="shadow p-1">
                        <h6 class="text-center">Words:</h6>
                        {% for i in words %}
                            <div class="row m-1">
                                <button class="author-btn">
                                    <a href="{% url 'userapp:wordedit' user_pk=user.pk author_pk=author_pk book_pk=book_pk word_pk=i.pk %}">{{ i.word }} - {{ i.translation }}</a>
                                </button>
                            </div>
                        {% endfor %}
                    </div>
                </div>

            </div>

        </div>
    </div>

{% endblock %}