authapp/urls.py
from django.urls import path, include
import authapp.views as authapp


app_name = 'authurls'
urlpatterns = [
    path('', authapp.login, name='authlogin'),
    path('logout/', authapp.logout, name='authlogout'),
    path('registration/', authapp.registration, name='authreg'),
]

# path('register/', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name='registration_register')

dictionary/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp



urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('authapp.urls', namespace='auth')), # в теплейтс, адрес ссылки для перехода на страницу логин,
                                                               # будет адрес auth:authlogin, где auth - это здешний
                                                               # namespace, а authlogin - name в authapp/urls
    path('userpage/', include('userapp.urls', namespace='userapp')),
    path('', mainapp.mainpage, name='mainpage'),
    path('userpage/excerpts/', include('excerptapp.urls', namespace='excerptapp')),
    path('userpage/phrases/', include('phraseapp.urls', namespace='phraseapp')),
]

authapp/models.py
from django.db import models

from django.contrib.auth.models import User, AbstractUser
from django.utils.timezone import now
from datetime import timedelta


# Create your models here.


class DictUser(AbstractUser):

    # class Meta(object):
    #     unique_together = ('email',)

    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'M'),
        (FEMALE, 'W'),
    )

    gender = models.CharField(verbose_name='gender', max_length=1, choices=GENDER_CHOICES, blank=True)
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='age', default=18)
    # activation_key = models.CharField(verbose_name='key conformation', max_length=128, blank=True)
    # activation_key_expires = models.DateTimeField(
    #     verbose_name='key relevance',
    #     default=(now() + timedelta(hours=48)))
    #
    # def is_activation_key_expired(self):
    #     if now() <= self.activation_key_expires:
    #         return False
    #     else:
    #         return True

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User, models
from django.forms import models

from .models import DictUser

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'placeholder':'Your login'
        }
    ))
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(
        attrs={
        'class':'form-control',
        'placeholder':'Your password'
        }
    ))


class RegistrationForm(UserCreationForm): #здесь буде пользовать заготовку, т.к. так делают почти везде, как задавать
    #два поля пароль на проверку не нашел

    class Meta:
        model = DictUser
        fields = ('username', 'password1', 'password2', 'email')

    #задать плейс отдельно каждому полю, затем все инпутам одинаковый класс
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'your nickname'
        self.fields['password1'].widget.attrs['placeholder'] = 'password'
        self.fields['password2'].widget.attrs['placeholder'] = 'confirm password'
        self.fields['email'].widget.attrs['placeholder'] = 'your email'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import LoginForm, RegistrationForm

# Create your views here.

# def login(request):
#     return render(request, 'authapp/login.html')

# def login(request):
#     if request.method == 'POST': # проверяем, какой пришел запрос, гет или пост
#         pass
#     else: #если не пост, то значит гет, а гет это просто отрисовка страницы, передадим форму на нее
#         form = LoginForm()
#
#         return render(request, 'authapp/login.html', {'login_form': form})



def login(request):
    if request.method == 'POST': # проверяем, какой пришел запрос, гет или пост
        # если пост, то нам нужно получить данные, которые нам отправили
        # создаем форму, в параметрах которой указываем данные, которые нам отправили request.POST (это свойства
        # хранящиеся ввиде словарей)
        form = LoginForm(request.POST)
        username = request.POST['username'] #словарь=значение по ключу username, то, что отправят в инпуте
        password = request.POST['password']
        #все, на данном этапе мы отрисовали форму логин страницы, полей инпута
        #далее пойдет систепа аутентификации

        #у нас теперь есть username и password, которые передаем во встроенную в джанго функцию
        user = auth.authenticate(username=username, password=password)
        #auth проверяет есть ли пользователь в базе и активный ли он
        if user and user.is_active:
            auth.login(request, user) #здесь логиним пользователя
            return HttpResponseRedirect(reverse('userapp:userpage'))
        else: #если пользователя нет или он не активный
            return render(request, 'authapp/login.html', {'login_form': form})
    else:  # если не пост, то значит гет, а гет это просто отрисовка страницы, передадим форму на нее; ИЛИ этот элс
        # в нашем случае будет отрисовать страницу при переходе на нее
        form = LoginForm()
        return render(request, 'authapp/login.html', {'login_form': form})

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('mainpage'))

def registration(request):
    if request.method == 'POST': #здесь аналогично предыдущему контролеру, принимаем данные отправленные методом пост (указывается в form в templates)
        form = RegistrationForm(request.POST) #request.FILE нужен если грузим файлы (у меня ща их нет, нет аватарки), а в form в templates добавляем enctype="multipart/form-data"
        if form.is_valid(): #проверка формы на валидацию и ее сохранение, зачем и как не знаю
            form.save()         #ну к примеру если один из паролей не совпадет, то ответ валидации будет false
            return HttpResponseRedirect(reverse('auth:authlogin'))


    else: #для гет сразу рисуем пустую форму, это вывод ее на экран
        form = RegistrationForm()

    return render(request, 'authapp/registration.html', {'registration_form': form})

authapp/templates/authapp/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <div class="wrapper">
        <div class="container-fluid text-center">
            <div class="row justify-content-center">
                <div class="col-xs-10 col-sm-8 col-md-6">

                    <div class="row">
                        <div class="col-sm-8 col-md-8 d-block mx-auto">
                            <img class="img-login img-fluid" src="/static/img/logo.png" alt="logo">
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-sm-10 col-md-10">
                            <h2>Dictionary</h2>
                        </div>
                    </div>
                    <form class="" action="{% url 'auth:authlogin' %}" method="post">
                        {% csrf_token %}
                        {% for i, k in login_form.errors.items %}
                            <div class="row">
                                {{ k }}
                            </div>
                        {% endfor %}
                        <div class="row justify-content-center">
                            {% for i in login_form %}
                                <div class="col-8 col-sm-8 col-md-8">
                                    {{ i }}
                                </div>

                            {% endfor %}
                        </div>
                        <div class="row justify-content-center">
                            <div class="col-sm-8 col-md-8">
                                <input class="logo-input-submit" type="submit" value="Sign In">
                            </div>
                        </div>
                    </form>
                    <div class="row justify-content-center">
                        <div class="col-sm-8 col-md-8">
                            <button class="logo-signup-btn" type="button"><a class="signup-btn" href="{% url 'auth:authreg' %}">Sign Up</a></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

authapp/templates/authapp/registration.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Registration</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <div class="wrapper-userpage">
        <div class="container-fluid text-center">
            <div class="row justify-content-center">
                <div class="col-xs-10 col-sm-8 col-md-6">

                    <div class="row justify-content-center">
                        <div class="col-sm-10 col-md-10">
                            <h2>Registration</h2>
                        </div>
                    </div>
                    <form class="" action="{% url 'auth:authreg' %}" method="post">
                        {% csrf_token %}
                        {% for i, k in login_form.errors.items %}
                            <div class="row">
                                {{ k }}
                            </div>
                        {% endfor %}
                        <div class="row justify-content-center">
                            {% for i in registration_form %}
                                <div class="col-8 col-sm-8 col-md-8" id="reg-helptext">
                                    {{ i }}
                                    {{ i.help_text }}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="row justify-content-center">
                            <div class="col-sm-8 col-md-8">
                                <input class="logo-input-submit" type="submit" value="Sign In">
                            </div>
                        </div>
                    </form>
                    <div class="row justify-content-center">
                        <div class="col-sm-8 col-md-8">
                            <button class="logo-signup-btn" type="button"><a class="signup-btn" href="{% url 'mainpage' %}">Main Page</a></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>