authapp/urls.py
from django.urls import path, include
import authapp.views as authapp


app_name = 'authurls'
urlpatterns = [
    path('', authapp.login, name='authlogin'),
    path('logout/', authapp.logout, name='authlogout'),
    path('registration/', authapp.registration, name='authreg'),
]

# path('register/', RegistrationView.as_view(form_class=RegistrationFormUniqueEmail), name='registration_register')

dictionary/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp



urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('authapp.urls', namespace='auth')), # в теплейтс, адрес ссылки для перехода на страницу логин,
                                                               # будет адрес auth:authlogin, где auth - это здешний
                                                               # namespace, а authlogin - name в authapp/urls
    path('userpage/', include('userapp.urls', namespace='userapp')),
    path('', mainapp.mainpage, name='mainpage'),
    path('userpage/excerpts/', include('excerptapp.urls', namespace='excerptapp')),
    path('userpage/phrases/', include('phraseapp.urls', namespace='phraseapp')),
]

excerptapp/urls.py
from django.urls import path, include
import excerptapp.views as excerptapp


app_name = 'excerptsurls'
urlpatterns = [
    path('<user_pk>/', excerptapp.createexcerpt, name='createexcerpts'),
    path('<user_pk>/<excerpt_pk>/', excerptapp.editexcerpt, name='editexcerpt')
]

userapp/urls.py
from django.urls import path, include
import userapp.views as userapp
from django.views import View


app_name = 'userdicturls'
urlpatterns = [
    path('', userapp.UserpageListView.as_view(), name='userpage'),
    path('<user_pk>/dictionaries', userapp.dictionaries, name='dictionaries'),
    # path('<user_pk>/dictionaries', userapp.DictionariesListView.as_view(), name='dictionaries'),
    path('<user_pk>/dictionaries/addauthor', userapp.addauthor, name='addauthor'),
    path('<user_pk>/dictionaries/<author_pk>/authoredit', userapp.authoredit, name='authoredit'),
    path('<user_pk>/dictionaries/<author_pk>/', userapp.books, name='books'),
    path('<user_pk>/dictionaries/<author_pk>/addbook', userapp.addbook, name='addbook'),
    path('<user_pk>/dictionaries/<author_pk>/<book_pk>/bookedit', userapp.bookedit, name='bookedit'),
    path('<user_pk>/dictionaries/<author_pk>/<book_pk>/', userapp.words, name='words'),
    path('<user_pk>/dictionaries/<author_pk>/<book_pk>/addword', userapp.addword, name='addword'),
    path('<user_pk>/dictionaries/<author_pk>/<book_pk>/edit/<word_pk>/', userapp.wordedit, name='wordedit'),
]

excerptapp/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class ExcerptModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_excerpt")
    source = models.CharField(verbose_name="Source", max_length=164)
    excerpt = models.CharField(verbose_name='Excerpt', max_length=128)
    translation = models.CharField(verbose_name='Excerpt_translation', max_length=128)

    def __str__(self):
        return "{}".format(self.excerpt)

excerptapp/forms.py
from django import forms
from .models import ExcerptModel

class ExcerptForm(forms.ModelForm):
    class Meta:
            model = ExcerptModel
            fields = ('source', 'excerpt', 'translation')

    def __init__(self, *args, **kwargs):
        super(ExcerptForm, self).__init__(*args, **kwargs)
        self.fields['source'].widget.attrs['placeholder'] = "Excerpt source"
        self.fields['excerpt'].widget.attrs['placeholder'] = "Excerpt"
        self.fields['translation'].widget.attrs['placeholder'] = "Excerpt translation"

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

excerptapp/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .forms import ExcerptForm
from .models import ExcerptModel

# Create your views here.

@login_required
def createexcerpt(request, user_pk):
    excerpt_items = ExcerptModel.objects.filter(user=request.user.pk)

    if request.method == 'POST':
        form = ExcerptForm(request.POST)
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.save()
            return HttpResponseRedirect(reverse('excerptapp:createexcerpts', args=[request.user.pk]))
    else:
        form = ExcerptForm()

    content = {
        'user_pk': request.user.pk,
        'excerpts': excerpt_items,
        'excerpt_form': form
    }

    return render(request, 'excerptapp/excerpts.html', content)

@login_required
@transaction.atomic
def editexcerpt(request, user_pk, excerpt_pk):
    excerpt_instance = get_object_or_404(ExcerptModel, pk=excerpt_pk)
    form = ExcerptForm(request.POST, instance=excerpt_instance)

    if request.method == 'POST':
        if form.is_valid():
            #следующие три строки отвечают за автоматическое добавление юзера в модель, поле юзер на экран не выводится
            response = form.save(commit=False)
            response.user = request.user
            response.save()
            return HttpResponseRedirect(reverse('excerptapp:createexcerpts', args=[request.user.pk]))
    else:
        form = ExcerptForm(instance=excerpt_instance)

    content = {
        'user_pk': request.user.pk,
        'excerpt_pk': excerpt_pk,
        'excerptedit_form': form
    }

    return render(request, 'excerptapp/excerptedit.html', content)

excerptapp/templates/excerptapp/excerptedit.html
{% extends "userapp/base.html" %}
{% load static %}
{% block back %}
    <li class="nav-item"><a href="{% url 'excerptapp:createexcerpts' user_pk=user.pk %}" class="nav-link">Back to Excerpts</a></li>
{% endblock %}
{% block content %}
    <div class="wrapper-userpage">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="shadow m-2 py-2">
                    <div class="col-sm-12 col-md-12">

                        <div class="row justify-content-center">
                            <div class="col-sm-12 col-md-12">
                                <p class="text-center">Excerpt edit form:</p>
                            </div>
                        </div>

                        <form class="" action="{% url 'excerptapp:editexcerpt' user_pk=user.pk excerpt_pk=excerpt_pk %}" method="post">
                            {% csrf_token %}

                            <div class="row">
                                {% for i in excerptedit_form %}
                                    <div class="col-sm-12 col-md-12">
                                        {{ i }}
                                    </div>
                                {% endfor %}
                            </div>

                            <div class="row">
                                <div class="col-sm-12 col-md-12">
                                    <input class="input-author" type="submit" value="Save">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

excerptapp/templates/excerptapp/excerpts.html
{% extends "userapp/base.html" %}
{% load static %}

{% block back %}
    <li class="nav-item"><a href="{% url 'userapp:userpage' %}" class="nav-link">Back to userpage</a></li>
{% endblock %}

{% block content %}
    <div class="wrapper-userpage">
        <div class="container-fluid">
            <div class="row justify-content-center">

                <div class="col-md-5 col-sm-12">
                    <div class="shadow p-1">
                        <h6 class="text-center">Add excerpt:</h6>
                        <form action="{% url 'excerptapp:createexcerpts' user_pk=user.pk %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                {% for i in excerpt_form %}
                                    {{ i }}
                                {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <input class="input-author" type="submit" value="Save">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-sm-12 col-md-5 my-1 no-paddings-x">
                    <div class="shadow py-1">
                        <h6 class="text-center">Your excerpts:</h6>
                    {% for i in excerpts %}
                        <div class="row m-1">
                            <button class="author-btn">
                                <a href="{% url 'excerptapp:editexcerpt' user_pk=user.pk excerpt_pk=i.pk %}">{{ i.excerpt }}</a>
                            </button>
                        </div>
                    {% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}